# Generated by Django 5.1.6 on 2025-03-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='availability_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='capacity_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('college_level', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='', max_length=20)),
                ('preferred_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='base.program')),
            ],
            options={
                'ordering': ['-preferred_date', '-created_at'],
                'unique_together': {('email', 'program', 'preferred_date', 'time_slot')},
            },
        ),
    ]
