# Generated by Django 5.1.6 on 2025-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('claimed', 'Claimed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
