# Generated by Django 5.1.6 on 2025-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='auto_approve_appointments',
            field=models.BooleanField(default=False),
        ),
    ]
