# Generated by Django 5.1.6 on 2025-03-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_program_auto_approve_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
