# Generated by Django 5.1.6 on 2025-03-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_examscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='application_number',
        ),
    ]
