# Generated by Django 5.1.6 on 2025-04-01 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_appointment_application_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(blank=True, null=True)),
                ('app_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_no', 'app_no'],
            },
        ),
        migrations.AddField(
            model_name='examscore',
            name='app_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='exam_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examscore',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_score', to='base.appointment'),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='examscore',
            index=models.Index(fields=['app_no'], name='base_examsc_app_no_b1f166_idx'),
        ),
        migrations.AddIndex(
            model_name='examscore',
            index=models.Index(fields=['exam_type'], name='base_examsc_exam_ty_9851a3_idx'),
        ),
        migrations.AddIndex(
            model_name='examscore',
            index=models.Index(fields=['name'], name='base_examsc_name_95e506_idx'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['app_no'], name='base_examre_app_no_8622d4_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_type'], name='base_examre_exam_ty_f04212_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['name'], name='base_examre_name_8aadf1_idx'),
        ),
    ]
