# Generated by Django 5.1.6 on 2025-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_testcenter_appointment_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test_center_address',
            field=models.TextField(blank=True, help_text='Copied from test_center.address', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_center_code',
            field=models.CharField(blank=True, help_text='Copied from test_center.code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_center_name',
            field=models.CharField(blank=True, help_text='Copied from test_center.name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_exam_date',
            field=models.DateField(blank=True, help_text='Copied from test_session.exam_date', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_exam_type',
            field=models.CharField(blank=True, help_text='Copied from test_session.exam_type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_reporting_time',
            field=models.CharField(blank=True, help_text='Calculated based on time_slot', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_room_code',
            field=models.CharField(blank=True, help_text='Copied from test_room.room_code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_room_name',
            field=models.CharField(blank=True, help_text='Copied from test_room.name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_session_status',
            field=models.CharField(blank=True, help_text='Copied from test_session.status', max_length=20, null=True),
        ),
    ]
