# Generated by Django 5.1.6 on 2025-04-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_appointment_test_center_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='test_center_address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_center_code',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_center_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_exam_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_exam_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_reporting_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_room_code',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_room_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_session_status',
        ),
    ]
