# Generated by Django 5.1.6 on 2025-04-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_appointment_test_center_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testroom',
            name='assigned_count',
            field=models.IntegerField(default=0, help_text='Number of students assigned to this room'),
        ),
        migrations.AddField(
            model_name='testroom',
            name='available_capacity',
            field=models.IntegerField(default=30, help_text='Available capacity (calculated as capacity - assigned_count)'),
        ),
    ]
