# Generated by Django 5.1.6 on 2025-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_testroom_assigned_count_testroom_available_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting_for_test_details', 'Waiting for Test Details'), ('waiting_for_submission', 'Waiting for Submission'), ('rejected', 'Rejected'), ('claimed', 'Claimed'), ('rescheduled', 'Rescheduled')], default='waiting_for_test_details', max_length=30),
        ),
    ]
