# Generated by Django 5.1.6 on 2025-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testroom',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM)')], default='morning', max_length=20),
        ),
    ]
