# Generated by Django 5.1.6 on 2025-04-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='oapr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Overall Ability Percentile Rank'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='part1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='English Proficiency'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='part2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Reading Comprehension'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='part3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Science Process Skills'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='part4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantitative Skills'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='part5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Abstract Thinking Skills'),
        ),
    ]
