# Generated by Django 5.1.6 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_examscore_exam_date_examscore_oapr_examscore_part1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_test_time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_time_slot_modified',
            field=models.BooleanField(default=False),
        ),
    ]
