# Generated by Django 4.2 on 2025-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waiting_for_test_details', 'Waiting for Test Details'), ('waiting_for_submission', 'Waiting for Submission'), ('rejected', 'Rejected'), ('claimed', 'Claimed'), ('rescheduled', 'Rescheduled'), ('submitted', 'Submitted')], default='waiting_for_test_details', max_length=30),
        ),
    ]
