# Generated by Django 4.2 on 2025-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['year'], name='base_examre_year_57a12b_idx'),
        ),
    ]
