# Generated by Django 4.2 on 2025-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_add_year_to_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddIndex(
            model_name='examscore',
            index=models.Index(fields=['year'], name='base_examsc_year_b66fd9_idx'),
        ),
    ]
