# Generated by Django 4.2 on 2025-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_appointment_first_name_appointment_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exam_date',
            field=models.DateField(blank=True, help_text='The actual exam date assigned to this appointment', null=True),
        ),
    ]
