# Generated by Django 4.2 on 2025-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_add_exam_date_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.URLField(blank=True, help_text='URL for announcement image', max_length=500, null=True),
        ),
    ]
