# Generated by Django 4.2 on 2025-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for announcement image (alternative to file upload)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Image file for announcement', null=True, upload_to='announcements/'),
        ),
    ]
