# Generated by Django 4.2 on 2025-07-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_scores', to='base.program'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, notification will be shown to all users'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional link to redirect when clicked', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('exam', 'Exam'), ('announcement', 'Announcement'), ('system', 'System'), ('reminder', 'Reminder')], default='system', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'priority'], name='base_notifi_type_5f75a1_idx'),
        ),
    ]
