# Generated by Django 4.2 on 2025-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_examscore_program_alter_notification_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disability_description',
            field=models.TextField(blank=True, help_text='Please describe the disability or special attention needed', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='father_citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='father_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='father_employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='father_monthly_income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='father_work_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_choice_campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_choice_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='has_physical_disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='indigenous_group_specify',
            field=models.CharField(blank=True, help_text='Please specify the Indigenous Peoples Group', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_indigenous_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='knows_computer_usage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother_citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother_employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother_monthly_income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother_work_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='religious_affiliation',
            field=models.CharField(blank=True, choices=[('roman_catholic', 'Roman Catholic'), ('protestant', 'Protestant'), ('islam', 'Islam'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='religious_affiliation_others',
            field=models.CharField(blank=True, help_text='Please specify if others', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='second_choice_campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='second_choice_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='third_choice_campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='third_choice_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
