# Generated by Django 4.2 on 2025-07-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_appointment_disability_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
